### ISSUE TITLE
no viable alternative at character '0'

### ISSUE THREAD

**Issue by KlaasBonnema** [thomas-fritsch/psdt#13]
Existing postscript files may contain sequences such as: def/CustomEnc[/00/01/02/03/04/05/06/07/08/09/0a/0b/0c/0d/0e/0f/10/11/12/13/14/15/16/17/18/19/zcaron/yacute/twosuperior/threesuperior.... ]
This array definition is marked in error for values /00 through /19 with "no viable alternative at character ".
The errors will prevent starting a debug session while this is perfectly valid postscript code that is accepted by all postscript interpreters.

**Comment by thomas-fritsch** [comment]
I could reproduce your error. It seems my [PostScript grammar](https://github.com/thomas-fritsch/psdt/blob/master/de.tfritsch.psdt/src/de/tfritsch/psdt/Postscript.xtext) is too strict for `terminal LITERAL_ID`, and may be also for `terminal ID`.
