### ISSUE TITLE
Cannot set a line breakpoint

### ISSUE THREAD

**Issue by glaukon-ariston** [thomas-fritsch/psdt#15]
The right click on the side bar shows a context menu with Toggle Breakpoint grayed out. Double click on the side bar doesn't create a breakpoint.

Eclipse Platform
Version: Neon.2 (4.6.2)
Build id: M20161124-1400

**Comment by thomas-fritsch** [comment]
Where in your file-system is your PostScript file?

- If **inside** of your Eclipse workspace (in one of your projects):  
  Setting breakpoints should work without problems.
- If **outside** of your Eclipse workspace:  
  The Eclipse plugin API supports breakpoints only for resources inside the workspace.
  Therefore it was not possible for me to offer PostScript breakpoints for files outside the workspace.  
  May be I should implement a warning about this restriction in a prominent place.

**Comment by glaukon-ariston** [comment]
You are right, it is outside the workspace -- I just draged and droped it in Eclipse. Will try putting it inside. Thanks.
