### ISSUE TITLE
Does this also work in eclips version 2021-03

### ISSUE THREAD

**Issue by Sicos1977** [thomas-fritsch/psdt#16]
I tried to set breakpoints but that does not seem to work and when running "the code" in debug mode I also don't see any stack output.

![image](https://user-images.githubusercontent.com/6692947/115148708-1b95b500-a061-11eb-85bd-1bf0c2dbc81d.png)

**Comment by thomas-fritsch** [comment]
I have tested it right now with Eclipse-2021-03 (on Windows 10), and for me it works.
In the editor-view you need to double-click into the narrow left columns
(either the column with the line-numbers, or the grey column left from that).
Or alternatively you need to right-click into these columns and select "Toggle breakpoint".
Either way, then you should have a blue bullet shown in the left-most column representing the breakpoint.

If all this doesn't work for you (for whatever reason), then you may want to checkmark the option
"Break on first token" in your debug configuration for your PostScript file.
